spring:
  profiles:
    active: local

---


server:
  port: 8080
  servlet:
    context-path: /user/api/v1

spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://gajoa-db1.cklyw6tgbrhb.ap-northeast-2.rds.amazonaws.com:3306/gajoa_test_db1
    username: admin
    password: rkdalsrb12#
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: 13.209.43.122
    port: 6379
    timeout: 1000
    password: rkdalsrb123$
---
jwt:
  secret: dkqjwlrkqkddpemfdjrktlsek
  accessToken:
    name: X-AUTH-TOKEN
    expireSecond: 60 # 60초
  refreshToken:
    name: X-REFRESH-TOKEN
    expireDay: 14 # 14일

cookie:
  expireTime: 60 # 60초



---
logging:
  config: classpath:log4j2.yml
---